# ═══════════════════════════════════════════════════════════════════
# messages.py — every user-visible message and error template
# ═══════════════════════════════════════════════════════════════════
# IMP: all .format() calls must match the placeholder names exactly;
#      tests assert on these strings, so wording changes here are breaking.

MSG_INFEASIBLE_CHILD_TOTAL: str = (
    "{parent_rows} {parent} x exactly {per_parent} {child} = {needed} {child}, "
    "but {requested} were requested. Raise {child} to at least {needed} "
    "or lower {child} per {parent} to {max_per_parent}."
)
MSG_UNSUPPORTED_RULE: str = "This request asked for something the engine cannot enforce: {detail}"
MSG_UPLOAD_EMPTY: str = "The file is empty."
MSG_UPLOAD_TOO_LARGE: str = "The upload is larger than {limit_mb} MB."
MSG_NO_TRACEBACK: str = "error occurred (no traceback available): {error}"
MSG_ERROR_DETAIL: str = "error occurred in python script [ {file} ], line [ {line} ], message [ {error} ]"

# spec_entity validation messages — one per vocabulary check
MSG_INVALID_GEN: str = "Unknown generator '{value}'. Allowed: {allowed}"
MSG_INVALID_DIST: str = "Unknown distribution '{value}'. Allowed: {allowed}"
MSG_INVALID_RULE: str = "Unknown rule '{value}'. Allowed: {allowed}"
MSG_INVALID_FAKER_FIELD: str = "Faker field '{value}' not in allowlist. Allowed: {allowed}"
MSG_INVALID_MODULE: str = "Unknown module '{value}'. Allowed: {allowed}"
MSG_INVALID_DEFECT_KIND: str = "Unknown defect kind '{value}'. Allowed: {allowed}"
MSG_INVALID_CARDINALITY_DIST: str = "Unknown cardinality distribution '{value}'. Allowed: {allowed}"

# llm / cloud messages
MSG_UNKNOWN_PROMPT_NAME: str = "Unknown prompt name '{name}'. Known prompts: {known}"
MSG_PROMPT_NOT_FOUND: str = "Prompt '{name}' not found at: {path}"
MSG_LLM_ALL_EXHAUSTED: str = "All LLM models and keys exhausted for prompt: {prompt_name}"
MSG_LLM_REPAIR_FAILED: str = "JSON repair failed after {retries} attempt(s) for: {prompt_name}"
MSG_COPULA_NO_NUMERIC: str = "CopulaFitter: No numeric columns found to fit."
MSG_GEN_AGGREGATE_MISSING_KEYS: str = "gen_aggregate: missing source_col or group_by in col_spec"
MSG_GEN_EXPR_EMPTY: str = "gen_expr: empty expression in col_spec, returning None series"

# sensitive-data / export notices
MSG_SYNTHETIC_DATA_NOTICE: str = (
    "SYNTHETIC DATA — generated by HackDataV2. "
    "Not real personal or financial data. "
    "Card numbers are published processor test cards only."
)
MSG_MASKED_COLUMNS: str = "Sensitive columns masked in output: {columns}"

# er_diagram
MSG_SCHEMA_NOT_RELATIONAL: str = "Schema diagram is only available for relational runs."
MSG_SCHEMA_NO_FK: str = "Schema diagram requires at least one foreign-key relationship."
MSG_SCHEMA_RUN_NOT_FOUND: str = "Run '{run_id}' not found."

# messiness
MSG_MESSINESS_RATE_TOO_HIGH: str = (
    "Rate {rate:.2f} exceeds the maximum allowed {max_rate:.2f} for setting '{setting}'."
)

# data mode — upload / generate / profile
MSG_DM_ROWS_TOO_HIGH: str = "n_rows {n} exceeds the maximum allowed {max_rows}."
MSG_DM_ROWS_TOO_LOW: str = "n_rows must be at least 1."
MSG_DM_UPLOAD_NOT_FOUND: str = "Upload '{run_id}' not found."
MSG_DM_NOT_ENOUGH_DATA: str = "not enough data"
MSG_DM_CONSTANT_COL: str = "constant"
MSG_DM_PROFILE_COLS_CAPPED: str = "Showing first {cap} of {total} columns in heatmap."

# ML Lab messages
MSG_ML_UNKNOWN_TASK:       str = "Unknown task_type '{value}'. Allowed: {allowed}"
MSG_ML_UNKNOWN_SOURCE:     str = "Unknown source_type '{value}'. Allowed: {allowed}"
MSG_ML_SIGNAL_OOB:         str = "signal_strength {value:.2f} must be in [0, 1]."
MSG_ML_NOISE_OOB:          str = "label_noise {value:.2f} must be in [0, {cap:.2f}]."
MSG_ML_TRAIN_RATIO_OOB:    str = "train_ratio {value:.2f} must be in [{lo:.2f}, {hi:.2f}]."
MSG_ML_ROWS_TOO_LOW:        str = "n_rows {n} is below minimum {min_rows}."
MSG_ML_ROWS_TOO_HIGH:       str = "n_rows {n} exceeds maximum {max_rows}."
MSG_ML_UNKNOWN_DRIVER:      str = "Driver column '{col}' not found in generated data."
MSG_ML_KEY_DRIVER:          str = "Column '{col}' looks like a key and cannot be a driver."
MSG_ML_TARGET_NOT_FOUND:    str = "Target column '{col}' not found in uploaded data."
MSG_ML_SINGLE_CLASS:        str = "Target column has only one class — ML check skipped."
MSG_ML_TOO_FEW_ROWS:        str = "Too few rows ({n}) for ML check — skipped."
MSG_ML_UPLOAD_NOT_FOUND:    str = "Upload run '{run_id}' not found."
MSG_ML_NO_QUERY:            str = "A query is required for source_type='describe'."
MSG_ML_CLASS_BALANCE_OOB:   str = "class_balance {value:.2f} must be in [{lo:.2f}, {hi:.2f}]."
